### ISSUE TITLE
Item order in subsequent iterations?

### ISSUE THREAD

**Issue by lavrentius-dev** [22222/CsvTextFieldParser#15]
More of a question than an issue: as function ParseCsvWithHeaderIgnoreErrors returns an IEnumerable<IDictionary<string, string>> collection, is the order of the items in the collection guaranteed in subsequent iterations? In other words, is the original (.csv) order of the lines preserved when iterating through the collection using foreach? In my tests it would seem so, yet discussions about IEnumerable suggest this is not the case (e.g., [here](https://stackoverflow.com/questions/10409893/ienumerable-and-order#:~:text=IEnumerable%20has%20no%20guaranteed%20order,you%20may%20have%20intrinsic%20order.)).

**Comment by 22222** [comment]
Yes, the order of lines from the ParseCsvWithHeaderIgnoreErrors function in the README file is guaranteed to be consistent on all iterations.

The IEnumerable interface itself doesn't provide any guarantee on the order of the rows because it's just an interface that could have any implementation.  So what matters for the order of the values in the IEnumerable is how it's implemented.

Distilling that README code down to a more basic implementation looks like this:

```c#
using (var csvReader = new StringReader(csvInput))
using (var parser = new NotVisualBasic.FileIO.CsvTextFieldParser(csvReader))
{
	while (!parser.EndOfData)
	{
		var fields = parser.ReadFields();
		yield return fields;
	}
}
```

The key part is the "yield return" statement.  That's what the C# compiler uses to generate the returned IEnumerable.  For more details, see:

- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/yield
- https://stackoverflow.com/questions/742497/yield-statement-implementation

So the values in the returned IEnumerable will always be in the same order because of how the C# "yield return" feature is implemented.

**Comment by lavrentius-dev** [comment]
Thank you! Your Csv parser is excellent, using it in this project: https://github.com/pegasone/cov2con
