### ISSUE TITLE
Can you please add ReadLine() method?

### ISSUE THREAD

**Issue by Krakean** [22222/CsvTextFieldParser#2]
Same like in TextFieldParser

**Comment by 22222** [comment]
I purposely left that out of this library because I didn't have any good use cases for it.  What use did you have in mind for that method?  I wouldn't necessarily be opposed to adding it if there's a good case I haven't thought of.

Otherwise, I can think of a couple alternative ways to get similar functionality that may or may not work depending on your needs.

One option would be to keep a copy of your TextReader and call that when you want to skip a line:

```c#
using (var csvReader = new StringReader(csvInput))
using (var parser = new NotVisualBasic.FileIO.CsvTextFieldParser(csvReader))
{
	var fields = parser.ReadFields();
	var line = csvReader.ReadLine();
}
```

But if you go with that route, be careful of calling the `HasNextLine` method on the parser since that will read ahead one line and keep a copy of it.  And this implementation isn't necessarily guaranteed for future versions of the library, so this maybe isn't an ideal solution.


Another option would be to create an extension method that recreates the line from the parsed fields:

```c#
public static class CsvTextFieldParserExtensions
{
	public static string ReadLine(this NotVisualBasic.FileIO.CsvTextFieldParser parser)
	{
		var fields = parser.ReadFields();
		if (fields == null) return null;
		
		return string.Join(",", fields.Select(SerializeValue));
	}

	private static string SerializeValue(string value)
	{
		if (value == null) return null;

		if (value.IndexOfAny(new char[] { ',', '"', '\n', '\r' }) >= 0)
		{
			return '"' + value.Replace("\"", "\"\"") + '"';
		}
		return value;
	}
}
```

Then you could call ReadLine with the same signature as the VB parser:

```c#
using (var csvReader = new StringReader(csvInput))
using (var parser = new NotVisualBasic.FileIO.CsvTextFieldParser(csvReader))
{
	string line;
	while ((line = parser.ReadLine()) != null)
	{
		yield return line;
	}
}
```


But this would not work exactly like the VB version if any of the field values contain an end-of-line character.  The VB version would read just until the first end-of-line character (stopping in the middle of the field), while this version would read the entire CSV row.  So that could be good or bad depending on what you're looking for.  It also wouldn't necessarily work correctly if you use custom delimiters or other options, although the extension method could probably be enhanced to read those custom values from the parser.

And there's always the option of just copying the source code into your own project and adding the method yourself.

**Comment by Krakean** [comment]
@22222 
Well, to be honest I dont know about use case. But it doesn't allow me to use your CsvTextFieldParser as drop-in replacement for original TextFieldParser.
I have some legacy code, which uses TextFieldParser, and use ReadLine() like this:
...
string inLine = parser.ReadLine();
string[] items = inLine.Split(',');
myItems = items;

bool toKeep = MyProcessLine(exchange,
                                      inLine, items, filePrefix, fileType,
                                       myCommodityCodesLookup, commodityGroupLookup,
                                       ref isRecordType30Passed,
                                       ref isRecordType40Passed,
                                       ref isRecordType50Passed);
if (toKeep)
{
        if (inLine != "")
        {
              myOutFile.WriteLine(inLine);
        }
}
...

And there is a lot of places similar to this.
Would be very nice if you can add ReadLine() like it was in original TextFieldParser, and let user decide the use case for it :)
In my case I wont use it, but I just need to keep legacy code compile with your CsvTextFieldParser as drop-in replacement.

And, thanks for your CsvTextFieldParser.

**Comment by 22222** [comment]
Thanks for the example.  In this case, I'd agree that you wouldn't necessarily want to use this library.  It seems like you'd be better off just using a TextReader (such as StringReader) directly.

The real VB TextFieldParser handles more than just CSV files, so this library was intended to be a subset with just parts needed for parsing CSV files.  And another goal is keeping this thing as simple as possible.  That `ReadLine` method doesn't really have anything to do with parsing CSV files, so that's why it was left out.

So I probably won't add it at this time.  But feel free to directly include the source code of the parser in your own project and add the method in if you decide you need it.  All of the code is in a single file to make that as easy as possible.
