### ISSUE TITLE
Cannot parse some csv file

### ISSUE THREAD

**Issue by Krakean** [22222/CsvTextFieldParser#4]
@22222 
https://nofile.io/f/oKHADXvTwwS/ICEProductCodeFile.csv - curious, why this file cannot be parsed? It fails with this error:
Line 2638 cannot be parsed because of trailing characters after an end quote.
and this:
Line 318 cannot be parsed because of trailing characters after an end quote.

Works fine with original TextFieldParser.

Stacktrace:
[16:30:48.248] [0.000]    at ICEProductCode.Helper.ProductCodeCache.ParseProductCodeContent(String dataContent) in ProductCodeCache.cs: 121
[16:30:48.248] [0.000]    at CsvTextFieldParser.ReadFields() in CsvTextFieldParser.cs: 121
[16:30:48.248] [0.000]    at CsvTextFieldParser.ParseField(String& line, Int32 startIndex, Int32& nextStartIndex) in CsvTextFieldParser.cs: 138
[16:30:48.248] [0.000]    at CsvTextFieldParser.ParseFieldAfterOpeningQuote(String& line, Int32 startIndex, Int32& nextStartIndex) in CsvTextFieldParser.cs: 290

Used in this context:
https://pastebin.com/7YrPwkd0

**Comment by 22222** [comment]
I tried parsing that file with your code and it seems to have worked without any errors for me.

Are you sure that's the same file you're getting the error on?  It looks like the file doesn't even contain any quote characters, so it's strange to have it report an error related to that.

One possibility is maybe there's something wrong with the string encoding?  I'd double check that the string you're passing into that method matches what's in the file (or whatever source you're reading from).

You could also try explicitly passing in the encoding you're using to see if that makes any difference:

```c#
parser = new CsvTextFieldParser(stream, Encoding.Default);
```

Or since you have the data as a string already, a `StringReader` might be easier to use than a MemoryStream:

```c#
var reader = new StringReader(dataContent);
parser = new CsvTextFieldParser(reader);
```

**Comment by Krakean** [comment]
@22222 
>I tried parsing that file with your code and it seems to have worked without any errors for me.

Sorry, wrong file. This one is correct link to the problematic file: https://www.theice.com/api/productguide/info/codes/all/csv

**Comment by 22222** [comment]
It looks like this parser and the VB version are consistent with throwing an error for that file.  The line at 318 looks roughly like this:

> `"=HYPERLINK(""http://url"",""Coffee "C" Calendar Spread Option"")","4137","KC1, KC2","KC1, KC2","","","Coffee","Coffee C","ICUS","IFUS","Coffee C"`

The problem is the double quotes in the first `Coffee "C"`.  You're already in a quoted field at that point, so the the first field ends up being just this:

> `"=HYPERLINK(""http://url"",""Coffee "`

That's immediately followed by the `C`, which is what causes the error.  At that point the parser is expecting a comma, newline, or end of file.

See the [error handling section of the readme](https://github.com/22222/CsvTextFieldParser#error-handling) for more details about parser errors.
