### ISSUE TITLE
Feature Request: LineNumber property

### ISSUE THREAD

**Issue by wrightsonm** [22222/CsvTextFieldParser#6]
The VB parser has a property LineNumber.
The parser internally has a lineNumber property.
Could it be exposed to make the interface similar to VB Parser please?

i.e. 
`public long LineNumber{get{return lineNumber;}}`

**Comment by 22222** [comment]
The main reason I hadn't exposed the LineNumber as a public property is because the value of that line number field doesn't currently match the VB parser in all cases.

But I'll add some tests for it and see if I can get it to match the VB parser, and then get the property added in the next release.
