### ISSUE TITLE
TrimWhiteSpace default value

### ISSUE THREAD

**Issue by drvic10k** [22222/CsvTextFieldParser#8]
VB parser has default value for TrimWhiteSpace true, while this parser has default value false

**Comment by 22222** [comment]
This library doesn't try to exactly match the defaults of the VB parser.  But that is probably something that should be better documented.

The VB parser works with any kind of file format, while this library is only focused on parsing CSV files.  So I tried to select defaults that are compatible the [CSV RFC 4180 standard](https://tools.ietf.org/html/rfc4180), which says this:

> Spaces are considered part of a field and should not be ignored.

But I will plan on updating the readme to point out and justify when the defaults are different than the VB parser.

**Comment by drvic10k** [comment]
sorry, I found it advertised as an 1:1 replacement for VB parser, also many issues here were comparing this to VB parser, so I thought that was the idea

**Comment by 22222** [comment]
No, you're right, this library is mostly designed to be compatible with the VB parser and the documentation didn't have any information about any differences being intentional.

I updated the compatibility section of the readme to include that information, including a line about the TrimWhitespace default value being different.  Let me know if that seems sufficient or if you think more information would be useful.

And at least for now, I'll plan on keeping the TrimWhitespace default value differences.  But if it causes a lot of problems for people, I'd maybe be open to reconsidering that decision.
